#**A Tutorial and Assessment on Python and NumPy for Deep Learning.**

# Python

4.1 Exercise on Functions:

In [ ]:
# Task 1 : Create a Python program that converts between different units of measurement.
def convert_units(conversion_type, value):
    """
    Convert units based on the specified conversion type.

    Parameters:
    conversion_type (str): The type of conversion ('m_to_ft', 'ft_to_m', 'kg_to_lbs', 'lbs_to_kg', 'L_to_gal', 'gal_to_L')
    value (float): The numeric value to convert

    Returns:
    float: The converted value
    """
    try:
        if conversion_type == "m_to_ft":
            return value * 3.28084
        elif conversion_type == "ft_to_m":
            return value / 3.28084
        elif conversion_type == "kg_to_lbs":
            return value * 2.20462
        elif conversion_type == "lbs_to_kg":
            return value / 2.20462
        elif conversion_type == "L_to_gal":
            return value * 0.264172
        elif conversion_type == "gal_to_L":
            return value / 0.264172
        else:
            return "Unsupported conversion type"
    except Exception as e:
        return f"Error: {e}"

# Map options to conversion types
conversion_map = {
    1: "m_to_ft",
    2: "ft_to_m",
    3: "kg_to_lbs",
    4: "lbs_to_kg",
    5: "L_to_gal",
    6: "gal_to_L"
}

print("Choose a conversion type:")
print("1. m to ft")
print("2. ft to m")
print("3. kg to lbs")
print("4. lbs to kg")
print("5. L to gal")
print("6. gal to L")

# Keep asking until valid input is provided
while True:
    try:
        choice = int(input("Enter option number (1-6): "))
        if choice not in conversion_map:
            print("Invalid option! Please choose a number between 1 and 6.")
            continue  # ask again

        value = float(input("Enter the value to convert: "))
        result = convert_units(conversion_map[choice], value)
        print(f"Converted value: {result}")
        break  # exit loop after successful conversion
    except ValueError:
        print("Invalid input! Please enter numeric values.")

Choose a conversion type:
1. m to ft
2. ft to m
3. kg to lbs
4. lbs to kg
5. L to gal
6. gal to L
Enter option number (1-6): 55
Invalid option! Please choose a number between 1 and 6.
Enter option number (1-6): 5
Enter the value to convert: 600
Converted value: 158.50320000000002


In [ ]:
# Task 2: Create a Python program that performs various mathematical operations on a list of numbers.

# Define functions for each operation

def calculate_sum(numbers):
    """Return the sum of a list of numbers."""
    return sum(numbers)

def calculate_average(numbers):
    """Return the average of a list of numbers."""
    return sum(numbers) / len(numbers)

def calculate_max(numbers):
    """Return the maximum value from a list of numbers."""
    return max(numbers)

def calculate_min(numbers):
    """Return the minimum value from a list of numbers."""
    return min(numbers)

# Prompt user to choose an operation
print("Choose an operation:")
print("1. Sum")
print("2. Average")
print("3. Maximum")
print("4. Minimum")

while True:
    try:
        choice = int(input("Enter option number (1-4): "))
        if choice not in [1, 2, 3, 4]:
            print("Invalid option! Please choose 1, 2, 3, or 4.")
            continue
        break
    except ValueError:
        print("Invalid input! Please enter a number.")

# Ask user how many numbers they want to process (must be >=2)
while True:
    try:
        n = int(input("How many numbers do you want to process? "))
        if n < 2:
            print("Please enter a number greater than 1.")
            continue
        break
    except ValueError:
        print("Invalid input! Please enter a valid number.")

# Collect the numbers one by one
numbers = []
for i in range(n):
    while True:
        try:
            num = float(input(f"Enter number {i+1}: "))
            numbers.append(num)
            break
        except ValueError:
            print("Invalid input! Please enter a numeric value.")

# Perform the selected operation
if choice == 1:
    result = calculate_sum(numbers)
    operation_name = "Sum"
elif choice == 2:
    result = calculate_average(numbers)
    operation_name = "Average"
elif choice == 3:
    result = calculate_max(numbers)
    operation_name = "Maximum"
else:
    result = calculate_min(numbers)
    operation_name = "Minimum"

print(f"{operation_name} of the numbers: {result}")

Choose an operation:
1. Sum
2. Average
3. Maximum
4. Minimum
Enter option number (1-4): 1
How many numbers do you want to process? 1
Please enter a number greater than 1.
How many numbers do you want to process? aa
Invalid input! Please enter a valid number.
How many numbers do you want to process? 2
Enter number 1: 22
Enter number 2: 22
Sum of the numbers: 44.0


4.2 Exercise on List Manipulation:

In [13]:
sample_list = [1, 2, 3, 4, 5, 6]

# 1. Extract every other element
def extract_every_other(lst):
    """Return every other element from the list, starting from the first."""
    return lst[::2]

# 2. Slice a Sublist:
def get_sublist(lst, start, end):
    """Return a sublist from start to end (inclusive)."""
    return lst[start:end+1]

# 3. Reverse a List Using Slicing:
def reverse_list(lst):
    """Return the reversed list using slicing."""
    return lst[::-1]

# 4. Remove the First and Last Elements:
def remove_first_last(lst):
    """Return the list without the first and last elements."""
    return lst[1:-1]

# 5. Get the First n Elements:
def get_first_n(lst, n):
    """Return the first n elements of the list."""
    return lst[:n]

# 6. Extract Elements from the End:
def get_last_n(lst, n):
    """Return the last n elements of the list."""
    return lst[-n:]

# 7. Extract Elements in Reverse Order:
def reverse_skip(lst):
    """Return every second element starting from the second-to-last, moving backward."""
    return lst[-2::-2]

print("Original list:", sample_list)
print("1. Every other element:", extract_every_other(sample_list))
print("2. Sublist from index 2 to 4:", get_sublist(sample_list, 2, 4))
print("3. Reversed list:", reverse_list(sample_list))
print("4. Remove first and last elements:", remove_first_last(sample_list))
print("5. First 3 elements:", get_first_n(sample_list, 3))
print("6. Last 2 elements:", get_last_n(sample_list, 2))
print("7. Reverse skip elements:", reverse_skip(sample_list))

Original list: [1, 2, 3, 4, 5, 6]
1. Every other element: [1, 3, 5]
2. Sublist from index 2 to 4: [3, 4, 5]
3. Reversed list: [6, 5, 4, 3, 2, 1]
4. Remove first and last elements: [2, 3, 4, 5]
5. First 3 elements: [1, 2, 3]
6. Last 2 elements: [5, 6]
7. Reverse skip elements: [5, 3, 1]


4.3 Exercise on Nested List:

In [16]:
nested_list = [[1, 2], [3, [4, 5]], [6, 2]]

# 1. Flatten a Nested List (one level):
def flatten(lst):
    """
    Flatten a nested list (one level).
    Here I used isinstance() to check if an element is a list.
    isinstance(item, list) : True if item is a list (or subclass of list)
    """
    result = []
    for item in lst:
        if isinstance(item, list):  # check if item is a list
            result.extend(item)
    return result

# 2. Accessing Nested List Elements:
def access_nested_element(lst, indices):
    """Access an element from a nested list using indices."""
    element = lst
    for idx in indices:
        element = element[idx]
    return element

# 3. Sum of All Elements in a Nested List:
def sum_nested(lst):
    """Return the sum of all numbers in a nested list (any depth).
    Here I used type() to check the type of item (simpler basic Python check).
    type(item) == list : True only if item is exactly a list
    """
    total = 0
    for item in lst:
        if type(item) == list:  # check if item is a list
            total += sum_nested(item)
        else:
            total += item
    return total

# 4. Remove Specific Element from a Nested List:
def remove_element(lst, elem):
    """Remove all occurrences of elem from a nested list (one level)."""
    result = []
    for item in lst:
        if type(item) == list:
            filtered = [x for x in item if x != elem]
            result.append(filtered)
        else:
            if item != elem:
                result.append(item)
    return result

# 5. Find the Maximum Element in a Nested List:
def find_max(lst):
    """Return the maximum element in a nested list (any depth)."""
    max_val = float('-inf')
    for item in lst:
        if type(item) == list:
            max_val = max(max_val, find_max(item))
        else:
            max_val = max(max_val, item)
    return max_val

# 6. Count Occurrences of an Element in a Nested List:
def count_occurrences(lst, elem):
    """Count how many times elem appears in a nested list (any depth)."""
    count = 0
    for item in lst:
        if type(item) == list:
            count += count_occurrences(item, elem)
        else:
            if item == elem:  # using '==' to check equality
                count += 1
    return count

# 7. Flatten a List of Lists of Lists:
def deep_flatten(lst):
    """Flatten a deeply nested list into a single list (any depth)."""
    result = []
    for item in lst:
        if type(item) == list:
            result.extend(deep_flatten(item))
        else:
            result.append(item)
    return result

# 8. Nested List Average:
def average_nested(lst):
    """Return the average of all elements in a nested list."""
    flat = deep_flatten(lst)
    return sum(flat) / len(flat)

print("Nested list:", nested_list)
print("1. Flatten:", flatten(nested_list))
print("2. Access element [1,1,0]:", access_nested_element(nested_list, [1,1,0]))
print("3. Sum nested:", sum_nested(nested_list))
print("4. Remove element 2:", remove_element(nested_list, 2))
print("5. Find max:", find_max(nested_list))
print("6. Count occurrences of 2:", count_occurrences(nested_list, 2))
print("7. Deep flatten:", deep_flatten(nested_list))
print("8. Nested average:", average_nested(nested_list))

Nested list: [[1, 2], [3, [4, 5]], [6, 2]]
1. Flatten: [1, 2, 3, [4, 5], 6, 2]
2. Access element [1,1,0]: 4
3. Sum nested: 23
4. Remove element 2: [[1], [3, [4, 5]], [6]]
5. Find max: 6
6. Count occurrences of 2: 2
7. Deep flatten: [1, 2, 3, 4, 5, 6, 2]
8. Nested average: 3.2857142857142856


# NumPy

In [20]:
import numpy as np

10.1 Basic Vector and Matrix Operation with Numpy.

In [22]:
# Problem - 1: Array Creation:

# 1. Initialize an empty array with size 2x2
empty_array = np.empty((2, 2))
print("1. Empty 2x2 array:\n", empty_array, "\n")

# 2. Initialize an all-one array with size 4x2
ones_array = np.ones((4, 2))
print("2. All ones 4x2 array:\n", ones_array, "\n")

# 3. Return a new array of given shape and type, filled with a fill value
fill_value = 7
shape = (3, 3)
filled_array = np.full(shape, fill_value, dtype=int)
print(f"3. Array of shape {shape} filled with {fill_value}:\n", filled_array, "\n")

# 4. Return a new array of zeros with same shape and type as a given array
zeros_like_array = np.zeros_like(filled_array)
print("4. Zeros array with same shape/type as filled_array:\n", zeros_like_array, "\n")

# 5. Return a new array of ones with same shape and type as a given array
ones_like_array = np.ones_like(filled_array)
print("5. Ones array with same shape/type as filled_array:\n", ones_like_array, "\n")

# 6. Convert an existing list to a numpy array
new_list = [1, 2, 3, 4]
array_from_list = np.array(new_list)
print("6. Numpy array from list [1,2,3,4]:\n", array_from_list)

1. Empty 2x2 array:
 [[4.9e-324 9.9e-324]
 [1.5e-323 2.0e-323]] 

2. All ones 4x2 array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]] 

3. Array of shape (3, 3) filled with 7:
 [[7 7 7]
 [7 7 7]
 [7 7 7]] 

4. Zeros array with same shape/type as filled_array:
 [[0 0 0]
 [0 0 0]
 [0 0 0]] 

5. Ones array with same shape/type as filled_array:
 [[1 1 1]
 [1 1 1]
 [1 1 1]] 

6. Numpy array from list [1,2,3,4]:
 [1 2 3 4]


In [23]:
# Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:
import numpy as np

# 1. Array with values from 10 to 49
arr1 = np.arange(10, 50)
print("1. Array from 10 to 49:\n", arr1, "\n")

# 2. 3x3 matrix with values from 0 to 8
arr2 = np.arange(9).reshape(3,3)
print("2. 3x3 matrix with values 0–8:\n", arr2, "\n")

# 3. 3x3 identity matrix
arr3 = np.eye(3)
print("3. 3x3 Identity matrix:\n", arr3, "\n")

# 4. Random array of size 30 and its mean
arr4 = np.random.random(30)
print("4. Random array of size 30:\n", arr4)
print("Mean of array:", arr4.mean(), "\n")

# 5. 10x10 random array and find min & max
arr5 = np.random.random((10,10))
print("5. 10x10 Random array:\n", arr5)
print("Minimum value:", arr5.min())
print("Maximum value:", arr5.max(), "\n")

# 6. Zero array of size 10 and replace 5th element with 1
arr6 = np.zeros(10)
arr6[4] = 1
print("6. Zero array with 5th element replaced by 1:\n", arr6, "\n")

# 7. Reverse an array
arr7 = np.array([1,2,0,0,4,0])
rev = arr7[::-1]
print("7. Reversed array:\n", rev, "\n")

# 8. 2D array with 1 on border and 0 inside
arr8 = np.ones((5,5))
arr8[1:-1,1:-1] = 0
print("8. 2D array with border 1 and inside 0:\n", arr8, "\n")

# 9. 8x8 checkerboard pattern
arr9 = np.zeros((8,8))
arr9[1::2, ::2] = 1
arr9[::2, 1::2] = 1
print("9. 8x8 Checkerboard pattern:\n", arr9)

1. Array from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49] 

2. 3x3 matrix with values 0–8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]] 

3. 3x3 Identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

4. Random array of size 30:
 [0.25158136 0.38324512 0.86354527 0.07387802 0.06681611 0.39208851
 0.32456395 0.29026577 0.40529615 0.74069843 0.56070968 0.07791585
 0.64278271 0.68464712 0.85829226 0.66456698 0.03014427 0.93720123
 0.19945562 0.61994191 0.20631752 0.12854819 0.28351115 0.42914539
 0.48519701 0.05392205 0.54090904 0.9153241  0.95730797 0.28813563]
Mean of array: 0.44519847853999484 

5. 10x10 Random array:
 [[0.42671717 0.3119511  0.98436715 0.30632363 0.74574842 0.02099239
  0.41476349 0.58646972 0.31056793 0.38502244]
 [0.1878083  0.40148205 0.86967985 0.16018646 0.13048437 0.06132077
  0.65360768 0.79930177 0.97231289 0.66937955]
 [0.3177137  0.4793801  0.54691634 0.9778593  0.64926782 0.44993424


In [24]:
# Problem - 3: Array Operations:

# Given arrays
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

print("x:\n", x)
print("y:\n", y)
print("v:", v)
print("w:", w)
print()

# 1. Add the two arrays
print("1. Addition of x and y:")
print(x + y)
print()

# 2. Subtract the two arrays
print("2. Subtraction of x and y:")
print(x - y)
print()

# 3. Multiply array with an integer (example: 3)
print("3. Multiply x with 3:")
print(x * 3)
print()

# 4. Square of each element
print("4. Square of elements in x:")
print(x ** 2)
print()

# 5. Dot products
print("5. Dot products:")

print("v · w =", np.dot(v, w))
print("x · v =")
print(np.dot(x, v))
print("x · y =")
print(np.dot(x, y))
print()

# 6. Concatenate arrays
print("6. Concatenate x and y along rows:")
print(np.concatenate((x, y), axis=0))

print("Concatenate v and w along column:")
print(np.concatenate((v.reshape(2,1), w.reshape(2,1)), axis=1))
print()

# 7. Concatenate x and v
print("7. Attempt to concatenate x and v:")

try:
    print(np.concatenate((x, v)))
except Exception as e:
    print("Error:", e)

print("\nExplanation: x is a 2D array (2x2) but v is a 1D array (size 2).")
print("They have different dimensions, so they cannot be concatenated directly.")

x:
 [[1 2]
 [3 5]]
y:
 [[5 6]
 [7 8]]
v: [ 9 10]
w: [11 12]

1. Addition of x and y:
[[ 6  8]
 [10 13]]

2. Subtraction of x and y:
[[-4 -4]
 [-4 -3]]

3. Multiply x with 3:
[[ 3  6]
 [ 9 15]]

4. Square of elements in x:
[[ 1  4]
 [ 9 25]]

5. Dot products:
v · w = 219
x · v =
[29 77]
x · y =
[[19 22]
 [50 58]]

6. Concatenate x and y along rows:
[[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenate v and w along column:
[[ 9 11]
 [10 12]]

7. Attempt to concatenate x and v:
Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

Explanation: x is a 2D array (2x2) but v is a 1D array (size 2).
They have different dimensions, so they cannot be concatenated directly.


In [26]:
# Problem - 4: Matrix Operations:

# Matrix Proofs
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

# 1. Prove A * A^-1 = I
A_inv = np.linalg.inv(A)
identity = np.dot(A, A_inv)

print("A inverse:\n", A_inv)
print("\nA * A^-1 =\n", identity)
print("Hence A.A^-1 = I proved\n")

# 2. Prove AB ≠ BA
AB = np.dot(A, B)
BA = np.dot(B, A)

print("AB =\n", AB)
print("\nBA =\n", BA)

if not np.array_equal(AB, BA):
    print("Hence AB ≠ BA proved\n")

# 3. Prove (AB)^T = B^T A^T
left = (AB).T
right = np.dot(B.T, A.T)

print("(AB)^T =\n", left)
print("\nB^T A^T =\n", right)

if np.array_equal(left, right):
    print("Hence (AB)^T = B^T A^T proved")

A inverse:
 [[-2.    1.  ]
 [ 1.75 -0.75]]

A * A^-1 =
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
Hence A.A^-1 = I proved

AB =
 [[23 13]
 [51 29]]

BA =
 [[36 44]
 [13 16]]
Hence AB ≠ BA proved

(AB)^T =
 [[23 51]
 [13 29]]

B^T A^T =
 [[23 51]
 [13 29]]
Hence (AB)^T = B^T A^T proved


In [29]:
# Solve Linear System Using Matrix Form

# Matrix A
A = np.array([
    [2, -3, 1],
    [1, -1, 2],
    [3, 1, -1]
])

# Matrix B
B = np.array([-1, -3, 9])

# Solve AX = B
X = np.linalg.solve(A, B)

print("Solution using np.linalg.solve:")
print("[x, y, z] =", X)

Solution using np.linalg.solve:
[x, y, z] = [ 2.  1. -2.]


In [30]:
# Solve using np.linalg.inv

A = np.array([
    [2, -3, 1],
    [1, -1, 2],
    [3, 1, -1]
])

B = np.array([-1, -3, 9])

# Inverse of A
A_inv = np.linalg.inv(A)

# X = A⁻¹B
X = np.dot(A_inv, B)

print("Solution using inverse method:")
print("[x, y, z] =", X)

Solution using inverse method:
[x, y, z] = [ 2.  1. -2.]


Method 1 (np.linalg.solve()) : Directly solves AX = B


Method 2 (np.linalg.inv()) : Uses formula Uses formula X = A^-1 B

10.2 Experiment: How Fast is Numpy?

In [31]:
import time
# 1. Element-wise Addition:
size = 1_000_000

# Python lists version
list1 = list(range(size))
list2 = list(range(size))

start = time.time()
result_list = [list1[i] + list2[i] for i in range(size)]
end = time.time()
print("Python list addition time:", end - start, "seconds")

# NumPy version
arr1 = np.arange(size)
arr2 = np.arange(size)

start = time.time()
result_np = arr1 + arr2
end = time.time()
print("NumPy array addition time:", end - start, "seconds")

Python list addition time: 0.12300395965576172 seconds
NumPy array addition time: 0.0039331912994384766 seconds


In [32]:
# 2. Element-wise Multiplication

# Python lists version
start = time.time()
result_list = [list1[i] * list2[i] for i in range(size)]
end = time.time()
print("Python list multiplication time:", end - start, "seconds")

# NumPy version
start = time.time()
result_np = arr1 * arr2
end = time.time()
print("NumPy array multiplication time:", end - start, "seconds")

Python list multiplication time: 0.15749096870422363 seconds
NumPy array multiplication time: 0.006136178970336914 seconds


In [33]:
# 3. Dot Product

# Python lists version
start = time.time()
dot_list = sum([list1[i] * list2[i] for i in range(size)])
end = time.time()
print("Python list dot product time:", end - start, "seconds")

# NumPy version
start = time.time()
dot_np = np.dot(arr1, arr2)
end = time.time()
print("NumPy dot product time:", end - start, "seconds")

Python list dot product time: 0.15979647636413574 seconds
NumPy dot product time: 0.0037050247192382812 seconds


In [36]:
# 4. Matrix Multiplication
# Python lists version
matrix_size = 500
mat1 = [[i+j for j in range(matrix_size)] for i in range(matrix_size)]
mat2 = [[i-j for j in range(matrix_size)] for i in range(matrix_size)]

start = time.time()
result = [[sum(mat1[i][k]*mat2[k][j] for k in range(matrix_size))
           for j in range(matrix_size)] for i in range(matrix_size)]
end = time.time()
print("Python list matrix multiplication time:", end - start, "seconds")

# NumPy version
np_mat1 = np.array(mat1)
np_mat2 = np.array(mat2)

start = time.time()
np_result = np.dot(np_mat1, np_mat2)
end = time.time()
print("NumPy array matrix multiplication time:", end - start, "seconds")

Python list matrix multiplication time: 20.903217792510986 seconds
NumPy array matrix multiplication time: 0.16957831382751465 seconds


From the experiment, we can see that NumPy operations are significantly faster than plain Python lists for large arrays and matrix computations. For example, element-wise addition and dot product were almost 40–50 times faster, and matrix multiplication was over 100 times faster with NumPy.

NumPy is faster because it does calculations on whole arrays at once, is written in fast C code, and stores data efficiently in memory.